export const FETCH_SUPPLIERS = 'FETCH_SUPPLIERS'
export const FETCH_SUPPLIER = 'FETCH_SUPPLIER'
export const FETCH_TOP_ITEMS = 'FETCH_TOP_ITEMS'
export const FETCH_SUPPLIERS_SORT = 'FETCH_SUPPLIERS_SORT'
